# Generated by Django 4.2.26 on 2025-12-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
