# Generated by Django 4.2 on 2025-11-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_codequestion_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='total_questions',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
